version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    target-branch: "main"
    open-pull-requests-limit: 10
    labels:
      - T:dependencies
      - S:automerge

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    target-branch: "v0.34.x"
    open-pull-requests-limit: 10
    labels:
      - T:dependencies
      - S:automerge

  - package-ecosystem: npm
    directory: "/docs"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10

  ###################################
  ##
  ## Update All Go Dependencies

  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: weekly
    target-branch: "main"
    open-pull-requests-limit: 10
    labels:
      - T:dependencies
      - S:automerge

  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: weekly
    target-branch: "v0.34.x"
    open-pull-requests-limit: 10
    labels:
      - T:dependencies
      - S:automerge
