version: '3'

services:
  node0:
    container_name: node0
    image: "tendermint/localnode"
    ports:
      - "46656-46657:46656-46657"
    environment:
      - ID=0
      - LOG=${LOG:-tendermint.log}
    volumes:
      - ${FOLDER:-./build}:/tendermint
    networks:
      localnet:
        ipv4_address: 10.100.0.2

  node1:
    container_name: node1
    image: "tendermint/localnode"
    ports:
      - "46659-46660:46656-46657"
    environment:
      - ID=1
      - LOG=${LOG:-tendermint.log}
    volumes:
      - ${FOLDER:-./build}:/tendermint
    networks:
      localnet:
        ipv4_address: 10.100.0.3

  node2:
    container_name: node2
    image: "tendermint/localnode"
    environment:
      - ID=2
      - LOG=${LOG:-tendermint.log}
    ports:
      - "46661-46662:46656-46657"
    volumes:
      - ${FOLDER:-./build}:/tendermint
    networks:
      localnet:
        ipv4_address: 10.100.0.4

  node3:
    container_name: node3
    image: "tendermint/localnode"
    environment:
      - ID=3
      - LOG=${LOG:-tendermint.log}
    ports:
      - "46663-46664:46656-46657"
    volumes:
      - ${FOLDER:-./build}:/tendermint
    networks:
      localnet:
        ipv4_address: 10.100.0.5

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 10.100.0.0/16

