---
- name: Add tendermint repository and key on CentOS/RedHat
  when: ansible_os_family == "RedHat"
  yum_repository:
    name: tendermint
    baseurl: http://tendermint-packages.s3-website-us-west-1.amazonaws.com/centos
    ui_repoid_vars: 7 os x86_64
    description: "Tendermint repo"
    gpgcheck: yes
    gpgkey: http://tendermint-packages.s3-website-us-west-1.amazonaws.com/centos/RPM-GPG-KEY-Tendermint
    repo_gpgcheck: yes

- name: Install package on CentOS/RedHat
  when: ansible_os_family == "RedHat"
  yum: pkg={{item}}
  with_items:
  - epel-release
  - jq
  - "{{service}}"

