---

#Three commands to install a service on Debian/Ubuntu
#wget -O - http://tendermint-packages.s3-website-us-west-1.amazonaws.com/centos/7/os/x86_64/RPM-GPG-KEY-Tendermint | apt-key add -
#echo "deb http://tendermint-packages.s3-website-us-west-1.amazonaws.com/debian stable main" > /etc/apt/sources.list.d/tendermint.list
#apt-get update && apt-get install basecoin

- name: Add repository key on Debian/Ubuntu
  when: ansible_os_family == "Debian"
  apt_key:
    url: http://tendermint-packages.s3-website-us-west-1.amazonaws.com/centos/7/os/x86_64/RPM-GPG-KEY-Tendermint
    id: 2122CBE9

- name: Install tendermint repository on Debian/Ubuntu
  when: ansible_os_family == "Debian"
  apt_repository:
    repo: deb http://tendermint-packages.s3-website-us-west-1.amazonaws.com/debian stable main

- name: Install package on Debian/Ubuntu
  when: ansible_os_family == "Debian"
  apt: "pkg={{service}} update_cache=yes state=latest"

