---
- name: Add repository key on Debian/Ubuntu
  when: ansible_os_family == "Debian"
  apt_key:
    url: http://tendermint-packages.s3-website-us-west-1.amazonaws.com/centos/7/os/x86_64/RPM-GPG-KEY-Tendermint
    id: 2122CBE9

- name: Install tendermint repository on Debian/Ubuntu
  when: ansible_os_family == "Debian"
  apt_repository:
    repo: deb http://tendermint-packages.s3-website-us-west-1.amazonaws.com/debian stable main

- name: Install package on Debian/Ubuntu
  when: ansible_os_family == "Debian"
  apt: pkg={{item}}
  with_items:
  - python-minimal
  - unzip
  - jq
  - "{{service}}"

