---
- name: gather OS specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_os_family }}-{{ ansible_distribution_major_version}}.yml"
    - "{{ ansible_os_family }}.yml"
- include: install.yml

