---

#variable "service" is required

- hosts: "{{ lookup('env','TF_VAR_TESTNET_NAME') }}:tag_Environment_{{ lookup('env','TF_VAR_TESTNET_NAME') }}"
  any_errors_fatal: "{{validators | bool | default(true)}}"
  roles:
    - install
    - {role: generic-service, when: service == 'tendermint'}
    - {role: config, testnet_name: "{{lookup('env','TF_VAR_TESTNET_NAME')}}"}
    - start

