---

#variable "service" is required

- hosts: "{{ lookup('env','TF_VAR_TESTNET_NAME') }}"
  roles:
    - install
    - {role: config, testnet_name: "{{lookup('env','TF_VAR_TESTNET_NAME')}}"}
    - start

