name: Documentation
# This workflow builds the static documentation site, and publishes the results to GitHub Pages.
# It runs on every push to the main branch, with changes in the docs and spec directories
on:
  workflow_dispatch:  # allow manual updates
  push:
    branches:
      - master
    paths:
      - "docs/**"
      - "spec/**"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    container:
      image: tendermintdev/docker-website-deployment
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3

      - name: Install and Build ğŸ”§
        run: |
          apk add rsync
          make build-docs
      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@v4.3.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: ~/output
          single-commit: true
