name: Check Markdown links

on:
  schedule:
    # 2am UTC daily
    - cron: '0 2 * * *'

jobs:
  markdown-link-check:
    strategy:
      matrix:
        branch: ['main', 'v0.37.x', 'v0.34.x']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ matrix.branch }}
      - uses: creachadair/github-action-markdown-link-check@master
        with:
          config-file: '.md-link-check.json'
