name: Net
# Net creates a 4 node test network with docker-compose
# This workflow is run on every pull request, if a *{.go, .mod, .sum} file has been modified, and push to master and release/** branches
on:
  pull_request:
    paths:
      - "**.go"
      - "**.mod"
      - "**.sum"
  push:
    branches:
      - master
      - release/**

jobs:
  net-short:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 10 Blocks
        run: |
          set -x
          docker run --rm -v "$PWD":/go/src/github.com/tendermint/tendermint -w /go/src/github.com/tendermint/tendermint golang make build-linux
          make localnet-start &
          ./scripts/localnet-blocks-test.sh 40 5 10 localhost
# Decide if we want to run longer lived testnets
