name: Proto Check
# Protobuf runs buf (https://buf.build/) lint and check-breakage
# This workflow is only run when a file in the proto directory
# has been modified.
on:
  workflow_dispatch:  # allow running workflow manually
  pull_request:
    paths:
      - "proto/**"

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v2
    - uses: bufbuild/buf-setup-action@v1.0.0
    - uses: bufbuild/buf-lint-action@v1
      with:
        input: 'proto'

  break-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bufbuild/buf-setup-action@v1.0.0
      - uses: bufbuild/buf-breaking-action@v1
        with:
          input: 'proto'
          against: 'https://github.com/${{ github.repository }}.git#branch=${{ github.event.pull_request.base.ref }},ref=HEAD~1,subdir=proto'
